---

- name: Add single node master to inventory
  ansible.builtin.add_host:
   name: "{{ master_ip }}"
   host_key_checking: false
   ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
   groups: "master"
  when: single_node == true

- name: Deploy K3s binaries
  hosts: k3s_cluster
  become: true
  gather_facts: true
  roles:
    - role: prereq
    - role: download
 
- name: Configuring master node
  hosts: master
  become: true
  roles:
    - role: k3s/master
 
- name: Configuring nodes
  hosts: node
  become: true
  roles:
    - role: k3s/node
  