---

- name: Deploy K3s binaries
  hosts: k3s_cluster
  become: true
  gather_facts: true
  roles:
    - prereq
    - download

- name: Setup master
  hosts: master
  become: true
  roles:
    - k3s/master

- name: Setup nodes
  hosts: node
  become: true
  roles:
    - k3s/node
